// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bczcghpwiasggfmutqrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjemNnaHB3aWFzZ2dmbXV0cXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTk5NjAsImV4cCI6MjA2MTE3NTk2MH0.l35QvcKO2hptBHs27stz7DXsL0MrWuOb0bNjx8sZZ_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);